[package]
name = "silang"
version = "0.3.0"
authors = ["Kaoru Chisen <cordx56@cordx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
nom = "6"
libloading = "0.7.0"
